import { Link } from "react-router-dom";
import { Footer } from "../../components/Footer";
import { NavBar } from "../../components/NavBar";
import { StarsBackground } from "../../components/StarsBackground";
import { TermSection } from "./components/TermSection";

export const TermsOfService = () => {
	return (
		<div className="scrollbar-thin scrollbar-thumb-ga-white-default scrollbar-track-ga-orangenut-darkest scrollbar flex min-h-screen flex-col justify-between gap-12 bg-ga-black-lighter">
			<StarsBackground />

			<div>
				<NavBar />
			</div>

			<div className="mx-auto flex max-w-5xl flex-col gap-12 px-4">
				<h2 className="text-3xl font-bold">
					Terms of Service for{" "}
					<span className="whitespace-nowrap">
						NUTPAL <span className="text-ga-orangenut-default">AI</span>
					</span>
				</h2>

				<div className="flex flex-col gap-4">
					<h3 className="text-lg font-bold italic">
						Effective Date: May 16, 2025
					</h3>
					<p className="italic">
						By accessing, utilizing, or visiting www.nutpal.ai (hereinafter
						referred to as "NUTPAL AI") or any of our communities, included but
						not limited to our communities on X and Discord (hereinafter
						referred to as "Communities"), including any content,
						functionalities, and services offered, you are indicating your
						acceptance and agreement to these Terms of Service ("Terms"), as
						well as our [Privacy Policy], which is included here within by
						reference. It is essential to review them periodically, as these
						terms may be updated from time to time without prior notice.
					</p>
					<p className="italic">
						These Terms are applicable to all users of the NUTPAL AI and our
						Communities. All such parties are collectively referred to as "you",
						"User", or "Users", as contextually appropriate, regardless of
						whether the NUTPAL AI and Communities are accessed via computer,
						mobile device, or any other technological medium or method. The
						Terms are an agreement formed between you and NUTPAL AI ("NUTPAL
						AI", "us", or "we").
					</p>
					<p className="italic">
						"Content" means any and all information and content that a user
						submits, including the text, software, scripts, graphics, photos,
						sounds, music, videos, audiovisual combinations, interactive
						features, textual content, and other materials you may view, upload,
						publish, submit, make available, display, communicate or post on the
						NUTPAL AI or Communities.
					</p>
				</div>

				<div className="flex flex-col gap-4">
					<TermSection level={1} content="1. Acceptable Use">
						<TermSection
							level={2}
							content="1.1. NUTPAL AI is intended for use solely for chat and role-play purposes. Users are not allowed to utilize the service for any illegal, malicious, or harmful activities that may infringe upon the rights of others."
						/>
						<TermSection
							level={2}
							content="1.2. You must be at least 18 years of age to use NUTPAL AI. If you're under the age of 18, you are not permitted to use our service or participate in any of our Communities."
						/>
					</TermSection>

					<TermSection level={1} content="2. Intellectual Property">
						<TermSection
							level={2}
							content="2.1. NUTPAL AI retains all intellectual property rights related to the project, including but not limited to the software, documentation, and any associated materials."
						/>
						<TermSection
							level={2}
							content="2.2. Users are granted a limited, non-exclusive, non-transferable license to use NUTPAL AI solely for personal, non-commercial purposes."
						/>
					</TermSection>

					<TermSection level={1} content="3. Code of Conduct">
						<TermSection
							level={2}
							content="3.1. Users are expected to engage respectfully and responsibly when using NUTPAL AI, refraining from engaging in offensive, abusive, or harmful behavior towards others."
						/>
						<TermSection
							level={2}
							content="3.2. Any Content generated using NUTPAL AI should not violate any applicable laws, including copyright,
				trademark, or privacy rights of third parties."
						/>
						<TermSection
							level={2}
							content="3.3. Users are prohibited from using NUTPAL AI to spread misinformation or engage in activities that could harm the reputation of the project."
						/>
					</TermSection>

					<TermSection level={1} content="4. Disclaimer of Warranty">
						<TermSection
							level={2}
							content='4.1. NUTPAL AI is provided "as is" without warranties of any kind, whether express or implied.'
						/>
						<TermSection
							level={2}
							content="4.2. While we strive to maintain accuracy, NUTPAL AI does not guarantee the correctness, reliability, or completeness of the information generated by the language model."
						/>
					</TermSection>

					<TermSection level={1} content="5. User Content and Responsibility">
						<TermSection
							level={2}
							content="5.1. Users are solely responsible for all Content they generate, submit, or share via NUTPAL AI or its Communities, including any prompts, responses, or media created through the service."
						/>
						<TermSection
							level={2}
							content="5.2. We do not monitor all Content, but we reserve the right to review, moderate, or remove any user Content that violates these Terms or applicable laws, at our sole discretion."
						/>
						<TermSection
							level={2}
							content="5.3. By using the service, you affirm that your Content does not infringe on any third-party rights, including intellectual property, privacy, or publicity rights."
						/>
					</TermSection>

					<TermSection level={1} content="6. Limitation of Liability">
						<TermSection
							level={2}
							content="6.1. In no event shall NUTPAL AI or its contributors be liable for any indirect, incidental, special, consequential, or punitive damages arising from the use of or inability to use the service."
						/>
						<TermSection
							level={2}
							content="6.2. NUTPAL AI shall not be held responsible for any content generated by the users or any third-party content accessed through the service."
						/>
					</TermSection>

					<TermSection level={1} content="7. Indemnification">
						<TermSection
							level={2}
							content="7.1. Users agree to indemnify and hold harmless NUTPAL AI and its contributors from any claims, damages, losses, or liabilities arising from their use of the service or any violation of these Terms of Service."
						/>
					</TermSection>

					<TermSection level={1} content="8. Suspension and Termination">
						<TermSection
							level={2}
							content="8.1. NUTPAL AI reserves the right to suspend or terminate access to the service at any time, with or without cause and without prior notice."
						/>
						<TermSection
							level={2}
							content="8.2. Upon termination, all provisions of these Terms of Service which by their nature should survive, including but not limited to intellectual property rights, warranty disclaimers, and limitations of liability, shall remain in effect."
						/>
					</TermSection>

					<TermSection level={1} content="9. Governing Law">
						<TermSection
							level={2}
							content="9.1. These Terms of Service shall be governed by and construed in accordance with the laws of local Jurisdiction, without regard to its conflicts of law principles."
						/>
					</TermSection>

					<TermSection level={1} content="10. Privacy Policy">
						<TermSection
							level={2}
							content="10.1. Please go to the link below to read our Privacy Policy:"
						>
							<Link to="/privacy"> Privacy Policy</Link>
						</TermSection>
					</TermSection>

					<TermSection level={1} content="11. Contact Us">
						<TermSection
							level={2}
							content="11.1. If you have any questions, suggestions or concerns, please send an email to [contact@nutpal.ai]."
						/>
					</TermSection>
				</div>
			</div>

			<Footer />
		</div>
	);
};
